version: "3.9"

services:
  server:
    image: ${IMAGE_FULL_NAME-{{cookiecutter.project_name}}}
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      ENV: production

  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:

volumes:
    postgres:
