version: "3.9"

services:
  server:
    image: ${IMAGE_FULL_NAME-test-docker-app}
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    depends_on:
      - postgres
    environment:
      ENV: production
    networks:
      - postgres

  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:

volumes:
    postgres:
